"""Add password reset fields to user

Revision ID: cd8d5cc651fb
Revises: 
Create Date: 2026-04-05 21:26:08.928856

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'cd8d5cc651fb'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_interests', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('idx_tag'))
        batch_op.drop_index(batch_op.f('unique_user_tag'))

    op.drop_table('user_interests')
    with op.batch_alter_table('moderator_metrics', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('idx_date'))
        batch_op.drop_index(batch_op.f('unique_moderator_date'))

    op.drop_table('moderator_metrics')
    with op.batch_alter_table('system_settings', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('setting_key'))

    op.drop_table('system_settings')
    with op.batch_alter_table('post_tags', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('idx_post_tags'))
        batch_op.drop_index(batch_op.f('idx_tag'))

    op.drop_table('post_tags')
    with op.batch_alter_table('appeals', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('idx_status'))
        batch_op.drop_index(batch_op.f('idx_type'))
        batch_op.drop_index(batch_op.f('idx_user_appeals'))
        batch_op.create_index(batch_op.f('ix_appeals_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_appeals_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_appeals_user_id'), ['user_id'], unique=False)

    with op.batch_alter_table('banned_keywords', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('idx_active'))
        batch_op.drop_index(batch_op.f('unique_keyword'))
        batch_op.create_index(batch_op.f('ix_banned_keywords_is_active'), ['is_active'], unique=False)
        batch_op.create_index(batch_op.f('ix_banned_keywords_keyword_normalized'), ['keyword_normalized'], unique=True)

    with op.batch_alter_table('comments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('idx_post_comments'))
        batch_op.drop_index(batch_op.f('idx_user_comments'))
        batch_op.create_index(batch_op.f('ix_comments_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_comments_post_id'), ['post_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_comments_user_id'), ['user_id'], unique=False)

    with op.batch_alter_table('friendships', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('idx_pending_requests'))
        batch_op.drop_index(batch_op.f('idx_user_friends'))
        batch_op.create_index(batch_op.f('ix_friendships_friend_id'), ['friend_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_friendships_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_friendships_user_id'), ['user_id'], unique=False)

    with op.batch_alter_table('likes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_likes_target_id'), ['target_id'], unique=False)

    with op.batch_alter_table('moderation_queue', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('idx_assigned'))
        batch_op.drop_index(batch_op.f('idx_status_priority'))
        batch_op.drop_index(batch_op.f('idx_target'))
        batch_op.create_index(batch_op.f('ix_moderation_queue_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_moderation_queue_priority'), ['priority'], unique=False)
        batch_op.create_index(batch_op.f('ix_moderation_queue_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_moderation_queue_target_id'), ['target_id'], unique=False)

    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('idx_notifications_actor_id'))
        batch_op.drop_index(batch_op.f('idx_user_notifications'))
        batch_op.create_index(batch_op.f('ix_notifications_actor_id'), ['actor_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_notifications_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_notifications_is_read'), ['is_read'], unique=False)
        batch_op.create_index(batch_op.f('ix_notifications_user_id'), ['user_id'], unique=False)
        batch_op.create_foreign_key(None, 'users', ['actor_id'], ['id'], ondelete='SET NULL')

    with op.batch_alter_table('post_media', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('idx_post_media'))
        batch_op.create_index(batch_op.f('ix_post_media_post_id'), ['post_id'], unique=False)

    with op.batch_alter_table('posts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('idx_ai_flagged'))
        batch_op.drop_index(batch_op.f('idx_moderation'))
        batch_op.drop_index(batch_op.f('idx_reports'))
        batch_op.drop_index(batch_op.f('idx_status'))
        batch_op.drop_index(batch_op.f('idx_user_posts'))
        batch_op.create_index(batch_op.f('ix_posts_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_posts_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_posts_user_id'), ['user_id'], unique=False)
        batch_op.drop_constraint(batch_op.f('posts_ibfk_2'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'users', ['moderator_id'], ['id'])

    with op.batch_alter_table('reports', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('idx_reporter'))
        batch_op.drop_index(batch_op.f('idx_status'))
        batch_op.drop_index(batch_op.f('idx_target'))
        batch_op.create_index(batch_op.f('ix_reports_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_reports_reporter_id'), ['reporter_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_reports_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_reports_target_id'), ['target_id'], unique=False)

    with op.batch_alter_table('shares', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('idx_post_shares'))
        batch_op.drop_index(batch_op.f('idx_user_shares'))
        batch_op.create_index(batch_op.f('ix_shares_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_shares_post_id'), ['post_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_shares_user_id'), ['user_id'], unique=False)

    with op.batch_alter_table('user_activity_logs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('activity_metadata', sa.JSON(), nullable=True))
        batch_op.drop_index(batch_op.f('idx_activity_type'))
        batch_op.drop_index(batch_op.f('idx_user_activity'))
        batch_op.create_index(batch_op.f('ix_user_activity_logs_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_activity_logs_user_id'), ['user_id'], unique=False)
        batch_op.drop_column('metadata')

    with op.batch_alter_table('user_blocks', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('idx_blocked'))
        batch_op.drop_index(batch_op.f('idx_blocker'))
        batch_op.create_index(batch_op.f('ix_user_blocks_blocked_id'), ['blocked_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_blocks_blocker_id'), ['blocker_id'], unique=False)

    with op.batch_alter_table('user_roles', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('idx_role'))
        batch_op.create_index(batch_op.f('ix_user_roles_role'), ['role'], unique=False)

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('reset_password_token', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('reset_password_token_created_at', sa.DateTime(), nullable=True))
        batch_op.drop_index(batch_op.f('email'))
        batch_op.drop_index(batch_op.f('idx_account_status'))
        batch_op.drop_index(batch_op.f('idx_email'))
        batch_op.drop_index(batch_op.f('idx_oauth'))
        batch_op.drop_index(batch_op.f('idx_username'))
        batch_op.drop_index(batch_op.f('username'))
        batch_op.create_index(batch_op.f('ix_users_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_users_username'), ['username'], unique=True)

    with op.batch_alter_table('violation_history', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('idx_severity'))
        batch_op.drop_index(batch_op.f('idx_user_violations'))
        batch_op.create_index(batch_op.f('ix_violation_history_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_violation_history_severity'), ['severity'], unique=False)
        batch_op.create_index(batch_op.f('ix_violation_history_user_id'), ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('violation_history', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_violation_history_user_id'))
        batch_op.drop_index(batch_op.f('ix_violation_history_severity'))
        batch_op.drop_index(batch_op.f('ix_violation_history_created_at'))
        batch_op.create_index(batch_op.f('idx_user_violations'), ['user_id', 'created_at'], unique=False)
        batch_op.create_index(batch_op.f('idx_severity'), ['severity', 'created_at'], unique=False)

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_username'))
        batch_op.drop_index(batch_op.f('ix_users_email'))
        batch_op.drop_index(batch_op.f('ix_users_created_at'))
        batch_op.create_index(batch_op.f('username'), ['username'], unique=True)
        batch_op.create_index(batch_op.f('idx_username'), ['username'], unique=False)
        batch_op.create_index(batch_op.f('idx_oauth'), ['oauth_provider', 'oauth_id'], unique=False)
        batch_op.create_index(batch_op.f('idx_email'), ['email'], unique=False)
        batch_op.create_index(batch_op.f('idx_account_status'), ['account_status'], unique=False)
        batch_op.create_index(batch_op.f('email'), ['email'], unique=True)
        batch_op.drop_column('reset_password_token_created_at')
        batch_op.drop_column('reset_password_token')

    with op.batch_alter_table('user_roles', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_roles_role'))
        batch_op.create_index(batch_op.f('idx_role'), ['role'], unique=False)

    with op.batch_alter_table('user_blocks', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_blocks_blocker_id'))
        batch_op.drop_index(batch_op.f('ix_user_blocks_blocked_id'))
        batch_op.create_index(batch_op.f('idx_blocker'), ['blocker_id'], unique=False)
        batch_op.create_index(batch_op.f('idx_blocked'), ['blocked_id'], unique=False)

    with op.batch_alter_table('user_activity_logs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('metadata', mysql.LONGTEXT(charset='utf8mb4', collation='utf8mb4_bin'), nullable=True))
        batch_op.drop_index(batch_op.f('ix_user_activity_logs_user_id'))
        batch_op.drop_index(batch_op.f('ix_user_activity_logs_created_at'))
        batch_op.create_index(batch_op.f('idx_user_activity'), ['user_id', 'created_at'], unique=False)
        batch_op.create_index(batch_op.f('idx_activity_type'), ['activity_type'], unique=False)
        batch_op.drop_column('activity_metadata')

    with op.batch_alter_table('shares', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_shares_user_id'))
        batch_op.drop_index(batch_op.f('ix_shares_post_id'))
        batch_op.drop_index(batch_op.f('ix_shares_created_at'))
        batch_op.create_index(batch_op.f('idx_user_shares'), ['user_id', 'created_at'], unique=False)
        batch_op.create_index(batch_op.f('idx_post_shares'), ['post_id', 'created_at'], unique=False)

    with op.batch_alter_table('reports', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_reports_target_id'))
        batch_op.drop_index(batch_op.f('ix_reports_status'))
        batch_op.drop_index(batch_op.f('ix_reports_reporter_id'))
        batch_op.drop_index(batch_op.f('ix_reports_created_at'))
        batch_op.create_index(batch_op.f('idx_target'), ['target_type', 'target_id', 'status'], unique=False)
        batch_op.create_index(batch_op.f('idx_status'), ['status', 'created_at'], unique=False)
        batch_op.create_index(batch_op.f('idx_reporter'), ['reporter_id'], unique=False)

    with op.batch_alter_table('posts', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('posts_ibfk_2'), 'users', ['moderator_id'], ['id'], ondelete='SET NULL')
        batch_op.drop_index(batch_op.f('ix_posts_user_id'))
        batch_op.drop_index(batch_op.f('ix_posts_status'))
        batch_op.drop_index(batch_op.f('ix_posts_created_at'))
        batch_op.create_index(batch_op.f('idx_user_posts'), ['user_id', 'created_at'], unique=False)
        batch_op.create_index(batch_op.f('idx_status'), ['status', 'created_at'], unique=False)
        batch_op.create_index(batch_op.f('idx_reports'), ['report_count', 'status'], unique=False)
        batch_op.create_index(batch_op.f('idx_moderation'), ['moderation_status', 'created_at'], unique=False)
        batch_op.create_index(batch_op.f('idx_ai_flagged'), ['ai_confidence_score', 'status'], unique=False)

    with op.batch_alter_table('post_media', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_post_media_post_id'))
        batch_op.create_index(batch_op.f('idx_post_media'), ['post_id', 'display_order'], unique=False)

    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_notifications_user_id'))
        batch_op.drop_index(batch_op.f('ix_notifications_is_read'))
        batch_op.drop_index(batch_op.f('ix_notifications_created_at'))
        batch_op.drop_index(batch_op.f('ix_notifications_actor_id'))
        batch_op.create_index(batch_op.f('idx_user_notifications'), ['user_id', 'is_read', 'created_at'], unique=False)
        batch_op.create_index(batch_op.f('idx_notifications_actor_id'), ['actor_id'], unique=False)

    with op.batch_alter_table('moderation_queue', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_moderation_queue_target_id'))
        batch_op.drop_index(batch_op.f('ix_moderation_queue_status'))
        batch_op.drop_index(batch_op.f('ix_moderation_queue_priority'))
        batch_op.drop_index(batch_op.f('ix_moderation_queue_created_at'))
        batch_op.create_index(batch_op.f('idx_target'), ['target_type', 'target_id'], unique=False)
        batch_op.create_index(batch_op.f('idx_status_priority'), ['status', 'priority', 'created_at'], unique=False)
        batch_op.create_index(batch_op.f('idx_assigned'), ['assigned_to', 'status'], unique=False)

    with op.batch_alter_table('likes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_likes_target_id'))

    with op.batch_alter_table('friendships', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_friendships_user_id'))
        batch_op.drop_index(batch_op.f('ix_friendships_status'))
        batch_op.drop_index(batch_op.f('ix_friendships_friend_id'))
        batch_op.create_index(batch_op.f('idx_user_friends'), ['user_id', 'status'], unique=False)
        batch_op.create_index(batch_op.f('idx_pending_requests'), ['friend_id', 'status', 'created_at'], unique=False)

    with op.batch_alter_table('comments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_comments_user_id'))
        batch_op.drop_index(batch_op.f('ix_comments_post_id'))
        batch_op.drop_index(batch_op.f('ix_comments_created_at'))
        batch_op.create_index(batch_op.f('idx_user_comments'), ['user_id', 'created_at'], unique=False)
        batch_op.create_index(batch_op.f('idx_post_comments'), ['post_id', 'created_at'], unique=False)

    with op.batch_alter_table('banned_keywords', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_banned_keywords_keyword_normalized'))
        batch_op.drop_index(batch_op.f('ix_banned_keywords_is_active'))
        batch_op.create_index(batch_op.f('unique_keyword'), ['keyword_normalized'], unique=True)
        batch_op.create_index(batch_op.f('idx_active'), ['is_active', 'severity'], unique=False)

    with op.batch_alter_table('appeals', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_appeals_user_id'))
        batch_op.drop_index(batch_op.f('ix_appeals_status'))
        batch_op.drop_index(batch_op.f('ix_appeals_created_at'))
        batch_op.create_index(batch_op.f('idx_user_appeals'), ['user_id', 'status'], unique=False)
        batch_op.create_index(batch_op.f('idx_type'), ['appeal_type', 'status'], unique=False)
        batch_op.create_index(batch_op.f('idx_status'), ['status', 'created_at'], unique=False)

    op.create_table('post_tags',
    sa.Column('id', mysql.BIGINT(display_width=20), autoincrement=True, nullable=False),
    sa.Column('post_id', mysql.BIGINT(display_width=20), autoincrement=False, nullable=False),
    sa.Column('tag', mysql.VARCHAR(length=100), nullable=False),
    sa.Column('confidence', mysql.DECIMAL(precision=5, scale=2), nullable=True),
    sa.ForeignKeyConstraint(['post_id'], ['posts.id'], name=op.f('post_tags_ibfk_1'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_unicode_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    with op.batch_alter_table('post_tags', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('idx_tag'), ['tag'], unique=False)
        batch_op.create_index(batch_op.f('idx_post_tags'), ['post_id'], unique=False)

    op.create_table('system_settings',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('setting_key', mysql.VARCHAR(length=100), nullable=False),
    sa.Column('setting_value', mysql.TEXT(), nullable=False),
    sa.Column('data_type', mysql.ENUM('string', 'number', 'boolean', 'json'), server_default=sa.text("'string'"), nullable=True),
    sa.Column('description', mysql.TEXT(), nullable=True),
    sa.Column('updated_by', mysql.BIGINT(display_width=20), autoincrement=False, nullable=True),
    sa.Column('updated_at', mysql.DATETIME(), server_default=sa.text('current_timestamp() ON UPDATE current_timestamp()'), nullable=True),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], name=op.f('system_settings_ibfk_1'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_unicode_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    with op.batch_alter_table('system_settings', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('setting_key'), ['setting_key'], unique=True)

    op.create_table('moderator_metrics',
    sa.Column('id', mysql.BIGINT(display_width=20), autoincrement=True, nullable=False),
    sa.Column('moderator_id', mysql.BIGINT(display_width=20), autoincrement=False, nullable=False),
    sa.Column('date', sa.DATE(), nullable=False),
    sa.Column('reviews_completed', mysql.INTEGER(display_width=11), server_default=sa.text('0'), autoincrement=False, nullable=True),
    sa.Column('avg_review_time_seconds', mysql.INTEGER(display_width=11), server_default=sa.text('0'), autoincrement=False, nullable=True),
    sa.Column('approvals', mysql.INTEGER(display_width=11), server_default=sa.text('0'), autoincrement=False, nullable=True),
    sa.Column('rejections', mysql.INTEGER(display_width=11), server_default=sa.text('0'), autoincrement=False, nullable=True),
    sa.Column('appeals_handled', mysql.INTEGER(display_width=11), server_default=sa.text('0'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['moderator_id'], ['users.id'], name=op.f('moderator_metrics_ibfk_1'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_unicode_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    with op.batch_alter_table('moderator_metrics', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('unique_moderator_date'), ['moderator_id', 'date'], unique=True)
        batch_op.create_index(batch_op.f('idx_date'), ['date'], unique=False)

    op.create_table('user_interests',
    sa.Column('id', mysql.BIGINT(display_width=20), autoincrement=True, nullable=False),
    sa.Column('user_id', mysql.BIGINT(display_width=20), autoincrement=False, nullable=False),
    sa.Column('tag', mysql.VARCHAR(length=100), nullable=False),
    sa.Column('interest_score', mysql.INTEGER(display_width=11), server_default=sa.text('1'), autoincrement=False, nullable=True),
    sa.Column('updated_at', mysql.DATETIME(), server_default=sa.text('current_timestamp() ON UPDATE current_timestamp()'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('user_interests_ibfk_1'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_unicode_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    with op.batch_alter_table('user_interests', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('unique_user_tag'), ['user_id', 'tag'], unique=True)
        batch_op.create_index(batch_op.f('idx_tag'), ['tag', 'interest_score'], unique=False)

    # ### end Alembic commands ###
